sudo: required
services:
  - docker

script:
  - docker build -t peterson1873/trade-logger .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-image
  on:
    branch: master
