sudo: required
services:
  - docker

script:
  - docker build -t peterson1873/trade-logger:1.0.0 .

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make push-image && cat ~/.docker/config.json
  on:
    branch: master
