FROM openjdk:8-jre-alpine3.8
RUN addgroup -S stockmailer && adduser -S -G stockmailer stockmailer
USER stockmailer
WORKDIR /home/stockmailer
ENTRYPOINT ["java","-jar", "-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n","/home/stockmailer/stockmailer-1.0.0-SNAPSHOT.jar"]
EXPOSE 443
EXPOSE 8787
