FROM openjdk:8-jre-alpine3.8
EXPOSE 80
EXPOSE 443
EXPOSE 8787

RUN apk update

WORKDIR /usr/app

ENTRYPOINT ["java","-jar", "-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n","/usr/app/stocklogger-1.0.0-SNAPSHOT.jar"]
