version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "443:8443"
      - "80:8080"
      - "8787:8787"
    volumes:
      - ./target:/home/stocklogger

