apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    component: web
spec:
  containers:
    - name: private-reg-container
      image: docker.io/peterson1873/trade-logger:1.0.0
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: regcred
